config/routes.rb
Rails.application.routes.draw do
  resources :securities do
    collection do
      get 'rsi'
    end
    member do
      get 'buy'
      post 'process_buy'
      get 'sell'
      post 'process_sell'
    end
  end

  devise_for :users
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    delete 'logout', :to => 'devise/sessions#destroy'
    get 'register', :to => 'registrations#new'
    get 'settings', :to => 'devise/registrations#edit'
  end
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'
end

app/models/security.rb
class Security < ActiveRecord::Base
  has_many :stock_day_logs, dependent: :destroy

  def display_class
    if percent_change_close > 0
      "gain"
    elsif percent_change_close < 0
      "loss"
    else
      ""
    end
  end

  def populate_closing_price
    day_logs = self.stock_day_logs.order("created_at desc").all
    last_log = day_logs.first
    if last_log.closing_price.blank?
      last_log.closing_price = previous_close
      last_log.save
    end

    (day_logs.length - 1).times do |i|
      next if day_logs[i + 1].closing_price.present?
      day_logs[i + 1].closing_price = day_logs[i].closing_price
      day_logs[i + 1].open_price = day_logs[i].closing_price
      day_logs[i + 1].high_price = day_logs[i].closing_price
      day_logs[i + 1].low_price = day_logs[i].closing_price
      day_logs[i + 1].save
    end
  end

  def populate_technicals
    populate_closing_price

    day_logs = self.stock_day_logs.order(:created_at).all
    (day_logs.length - 9).times do |i|
      day_logs[9 + i].sma_10 = (day_logs[(0 + i)..(9 + i)].sum(&:closing_price) / 10).round(3)
    end
    if day_logs.length >= 12
      day_logs[11].ema_12 = (day_logs[0..11].sum(&:closing_price) / 12).round(3)
    end
    if day_logs.length >= 15
      day_logs[14].ema_14_up = (day_logs[1..14].sum(&:upward_change) / 14).round(3)
      day_logs[14].ema_14_down = (day_logs[1..14].sum(&:downward_change) / 14).round(3)
    end
    if day_logs.length >= 26
      day_logs[25].ema_26 = (day_logs[0..25].sum(&:closing_price) / 26).round(3)
    end
    if day_logs.length >= 30
      day_logs[29].ema_30 = (day_logs[0..29].sum(&:closing_price) / 30).round(3)
    end

    (9..(day_logs.length - 1)).each do |i|
      if i > 11
        day_logs[i].ema_12 = (day_logs[i].closing_price * (2.0/13.0) + day_logs[i - 1].ema_12 * (1 - (2.0/13.0))).round(3)
      end
      if i > 14
        day_logs[i].ema_14_up = (day_logs[i].upward_change * (2.0/15.0) + day_logs[i - 1].ema_14_up * (1.0 - (2.0/15.0))).round(3)
        day_logs[i].ema_14_down = (day_logs[i].downward_change * (2.0/15.0) + day_logs[i - 1].ema_14_down * (1.0 - (2.0/15.0))).round(3)

        if day_logs[i].ema_14_down < 0.001
          if day_logs[i].ema_14_up < 0.001 
            day_logs[i].rsi = 50.0
          else
            day_logs[i].rsi = 100.0
          end
        else
          day_logs[i].rsi = (100.0 - (100.0/(1.0+(day_logs[i].ema_14_up / day_logs[i].ema_14_down)))).round(3)
        end
      end
      if i > 25
        day_logs[i].ema_26 = (day_logs[i].closing_price * (2.0/27.0) + day_logs[i - 1].ema_26 * (1 - (2.0/27.0))).round(3)
      end
      if i > 29
        day_logs[i].ema_30 = (day_logs[i].closing_price * (2.0/31.0) + day_logs[i - 1].ema_30 * (1 - (2.0/31.0))).round(3)
      end
      if i == 33
        day_logs[33].macd_signal = (day_logs[25..33].sum(&:macd) / 9).round(3)
        day_logs[33].macd_divergence = day_logs[33].macd - day_logs[33].macd_signal 
      end
      if i > 33
        day_logs[i].macd_signal = (day_logs[i].macd * (2.0/10.0) + day_logs[i - 1].macd_signal * (1 - (2.0/10.0))).round(3)
        day_logs[i].macd_divergence = day_logs[i].macd - day_logs[i].macd_signal 
      end
      day_logs[i].save
    end
  end

  def calculate_day_technicals
    day_logs = self.stock_day_logs.order(:created_at).all

    if day_logs.length >= 10
      day_logs[-1].sma_10 = (day_logs[-10..-1].sum(&:closing_price) / 10).round(3)
    end

    if day_logs.length == 12
      day_logs[11].ema_12 = (day_logs[0..11].sum(&:closing_price) / 12).round(3)
    end
    if day_logs.length > 12
      day_logs[-1].ema_12 = (day_logs[-1].closing_price * (2.0/13.0) + day_logs[-2].ema_12 * (1.0 - (2.0/13.0))).round(3)
    end

    if day_logs.length == 15
      day_logs[14].ema_14_up = (day_logs[1..14].sum(&:upward_change) / 14).round(3)
      day_logs[14].ema_14_down = (day_logs[1..14].sum(&:downward_change) / 14).round(3)
    end

    if day_logs.length > 15
      day_logs[-1].ema_14_up = (day_logs[-1].upward_change * (2.0/15.0) + day_logs[-2].ema_14_up * (1.0 - (2.0/15.0))).round(3)
      day_logs[-1].ema_14_down = (day_logs[-1].downward_change * (2.0/15.0) + day_logs[-2].ema_14_down * (1.0 - (2.0/15.0))).round(3)

      if day_logs[-1].ema_14_down < 0.001
        if day_logs[-1].ema_14_up < 0.001 
          day_logs[-1].rsi = 50.0
        else
          day_logs[-1].rsi = 100.0
        end
      else
        day_logs[-1].rsi = (100.0 - (100.0/(1.0+(day_logs[-1].ema_14_up / day_logs[-1].ema_14_down)))).round(3)
      end
    end

    if day_logs.length == 26
      day_logs[25].ema_26 = (day_logs[0..25].sum(&:closing_price) / 26).round(3)
    end

    if day_logs.length > 26
      day_logs[-1].ema_26 = (day_logs[-1].closing_price * (2.0/27.0) + day_logs[-2].ema_26 * (1.0 - (2.0/27.0))).round(3)
    end

    if day_logs.length == 30
      day_logs[29].ema_30 = (day_logs[0..29].sum(&:closing_price) / 30).round(3)
    end
    if day_logs.length > 30
      day_logs[-1].ema_30 = (day_logs[-1].closing_price * (2.0/31.0) + day_logs[-2].ema_30 * (1.0 - (2.0/31.0))).round(3)
    end

    if day_logs.length == 34
      day_logs[33].macd_signal = (day_logs[25..33].sum(&:macd) / 9).round(3)
      day_logs[33].macd_divergence = day_logs[33].macd - day_logs[33].macd_signal 
    end
    if day_logs.length > 34
      day_logs[-1].macd_signal = (day_logs[-1].macd * (2.0/10.0) + day_logs[-2].macd_signal * (1.0 - (2.0/10.0))).round(3)
      day_logs[-1].macd_divergence = day_logs[-1].macd - day_logs[-1].macd_signal 
    end
    day_logs[-1].save
  end
end

app/controllers/securities_controller.rb
class SecuritiesController < ApplicationController
  before_action :authenticate_user!, only: [:buy, :process_buy, :sell, :process_sell]
  def index
    @securities = Security.order(:symbol).all
    @day_ticker_log = DayTickerLog.last
  end

  def rsi
    @day_ticker_log = DayTickerLog.last
    @securities = @day_ticker_log.securities.order("stock_day_logs.rsi").all
  end

  def show
    @security = Security.find(params[:id])
    @day_ticker_log = DayTickerLog.last
    history = StockDayLog.find_by_sql([
      "SELECT 
         log_at, open_price, high_price, low_price, closing_price, volume_traded,
         sma_10, ema_30, (ema_12 - ema_26) as macdt, macd_signal, macd_divergence, 
         rsi
       FROM stock_day_logs
       INNER JOIN day_ticker_logs
         ON (stock_day_logs.day_ticker_log_id = day_ticker_logs.id)
       WHERE stock_day_logs.security_id = ? AND high_price IS NOT NULL
       ORDER BY stock_day_logs.created_at", @security.id])
    @json_history = JSON.generate(history.map do |d|
      [d.log_at.to_datetime.to_i * 1000,
       d.open_price.to_f,
       d.high_price.to_f,
       d.low_price.to_f,
       d.closing_price.to_f, 
       d.volume_traded.to_i,
       (d.sma_10.nil? ? nil : d.sma_10.to_f),
       (d.ema_30.nil? ? nil : d.ema_30.to_f),
       (d.macdt.nil? ? nil : d.macdt.to_f),
       (d.macd_signal.nil? ? nil : d.macd_signal.to_f),
       (d.macd_divergence.nil? ? nil : d.macd_divergence.to_f),
       (d.rsi.nil? ? nil : d.rsi.to_f)
      ]
    end)
  end

  def buy
    @security = Security.find(params[:id])
    @transaction = current_user.portfolio_transactions.build
  end

  def sell
    @security = Security.find(params[:id])
  end
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/securities/buy.html.haml
%h1 Buy Stock

%h2
  = @security.company_name 
  = "(#{@security.symbol})"

.row
  .col-md-4
    %table.table.table-condensed.table-striped
      %tr
        %td Last Trade Price
        %td.text-right= number_with_precision @security.last_price, precision: 2, delimiter: ','
      %tr
        %td Open
        %td.text-right= number_with_precision @security.open_price, precision: 2, delimiter: ','
      %tr
        %td Board Lot
        %td.text-right= number_with_delimiter @security.board_lot
  .col-md-4
    %table.table.table-condensed.table-striped
      %tr
        %td High
        %td.text-right= number_with_precision @security.high_price, precision: 2, delimiter: ','
      %tr
        %td Low
        %td.text-right= number_with_precision @security.low_price, precision: 2, delimiter: ','
  .col-md-4
    %table.table.table-condensed.table-striped
      %tr
        %td Volume
        %td.text-right= number_with_delimiter @security.volume_traded.to_i
      %tr
        %td % Change
        %td.text-right{ class: @security.display_class }
          = number_with_precision @security.percent_change_close, precision: 2

.row
  .col-md-6
    = simple_form_for @transaction, url: process_buy_security_path(@security) do |f|
      = f.input :shares, hint: "Must be in multiples of #{@security.board_lot}"

app/views/securities/index.html.haml
.row
  .col-md-10
    %h1 List of Companies
    %p
      As of
      = l @day_ticker_log.ticker_logs.last.ticker_as_of

    %table.table.table-condensed.table-striped
      %tr
        %th.text-center Company Name
        %th.text-center Symbol
        %th.text-center Price
        %th.text-center % Change
        - if user_signed_in?
          %th
      - @securities.each do |stock|
        %tr
          %td= link_to stock.company_name, stock
          %td= stock.symbol
          %td.text-right= number_with_precision stock.last_price, precision: 2, delimiter: ','
          %td.text-right{ class: stock.display_class }
            = number_with_precision stock.percent_change_close, precision: 2
          - if user_signed_in?
            %td.text-right
              = link_to "Buy", buy_security_path(stock), :class => "btn btn-default btn-xs"
              = link_to "Sell", sell_security_path(stock), :class => "btn btn-default btn-xs"
  .col-md-2
    = render "shared/ads"

app/views/securities/rsi.html.haml
.row
  .col-md-10
    %h1 List of Companies
    %p
      As of
      = l @day_ticker_log.ticker_logs.last.ticker_as_of

    %table.table.table-condensed.table-striped
      %tr
        %th.text-center Company Name
        %th.text-center Symbol
        %th.text-center Price
        %th.text-center % Change
        %th.text-center Volume
        %th.text-center RSI
        - if user_signed_in?
          %th
      - @securities.each do |stock|
        %tr
          %td= link_to stock.company_name, stock
          %td= stock.symbol
          %td.text-right= number_with_precision stock.last_price, precision: 2, delimiter: ','
          %td.text-right{ class: stock.display_class }
            = number_with_precision stock.percent_change_close, precision: 2
          %td.text-right= number_with_precision stock.volume_traded, precision: 2, delimiter: ','
          %td.text-right
            = number_with_precision stock.stock_day_logs.where(day_ticker_log: @day_ticker_log).first.rsi, precision: 2
          - if user_signed_in?
            %td.text-right
              = link_to "Buy", buy_security_path(stock), :class => "btn btn-default btn-xs"
              = link_to "Sell", sell_security_path(stock), :class => "btn btn-default btn-xs"
  .col-md-2
    = render "shared/ads"

app/views/securities/show.html.haml
- content_for :data_scripts do
  :javascript
    window.Stock = "#{@security.symbol}";
    window.StockData = #{raw @json_history};

.row
  .col-md-10
    %h1= @security.company_name 
    %h2= @security.symbol 

    %p
      As of
      = @day_ticker_log.ticker_logs.last.ticker_as_of
    %table.table.table-condensed.table-striped
      %tr
        %td Last Trade Price
        %td.text-right= number_with_precision @security.last_price, precision: 2, delimiter: ','
      %tr
        %td Open
        %td.text-right= number_with_precision @security.open_price, precision: 2, delimiter: ','
      %tr
        %td High
        %td.text-right= number_with_precision @security.high_price, precision: 2, delimiter: ','
      %tr
        %td Low
        %td.text-right= number_with_precision @security.low_price, precision: 2, delimiter: ','
      %tr
        %td Volume
        %td.text-right= number_with_delimiter @security.volume_traded.to_i
      %tr
        %td % Change
        %td.text-right{ class: @security.display_class }
          = number_with_precision @security.percent_change_close, precision: 2
    #chart-container{ style: "height: 900px;min-width: 310px"}
  .col-md-2
    = render "shared/ads"