config/routes.rb
Rails.application.routes.draw do
  resources :securities do
    collection do
      get 'rsi'
    end
    member do
      get 'buy'
      post 'process_buy'
      get 'sell'
      post 'process_sell'
    end
  end

  devise_for :users
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    delete 'logout', :to => 'devise/sessions#destroy'
    get 'register', :to => 'registrations#new'
    get 'settings', :to => 'devise/registrations#edit'
  end
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title PSE Paper Trading Game
    -#= display_meta_tags :site => ENV['title'], :reverse => true
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}/
  %body
    .navbar.navbar-static-top.navbar-default
      .container
        .navbar-header
          %button.navbar-toggle{ "type" => "button", "data-toggle" => "collapse", "data-target" => ".navbar-collapse" }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "PSE Paper Trading Game", root_url, :class => "navbar-brand"
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            -#%li{ :class => (action_name == "podcasts" ? "active" : "") }= link_to "Podcasts", podcasts_url
            %li{ :class => ((action_name == "index" && controller_name == "pages") ? "active" : "") }= link_to "Home", root_url
            %li{ :class => (controller_name == "securities" ? "active" : "") }= link_to "Stocks", securities_url
          -#= form_tag search_path, method: :get, class: "navbar-form navbar-right" do
            -#.form-group
              -#= text_field_tag "q", params[:q], class: "form-control"
            -#%button.btn.btn-default{ type: "submit" }
              -#%i.glyphicon.glyphicon-search
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              -#%li= link_to 'Profile', current_user
              -#%li= link_to 'Settings', settings_path
              -#%li.divider
              %li= link_to current_user.email, "#"
              %li= link_to 'Sign out', logout_path, :method => :delete
            - else
              %li= link_to 'Sign up', new_user_registration_path
              %li= link_to 'Sign in', login_path


    .container.main-container
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name == "notice" ? "success" : "danger"}"}
          %a.close{"data-dismiss" => "alert"} ×
          = msg
      .row
        .col-sm-12
          = yield
    %footer
      .container
        %p
          &copy; 2015
          = link_to "Bryan Bibat", "http://bryanbibat.net"
        %p
          This game is for educational purposes only and has no relation with PSE or any of the companies featured.
          -#%br
          -#= link_to "Fork this on Github", "https://github.com/phrug/pinoyrb"

    -#= javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry"
    -#= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"
    = yield :data_scripts
    = javascript_include_tag "application"
    = yield :scripts
    -#= render "layouts/analytics"